[tool.poetry]
name = "obsidian-rag"
version = "0.1.0"
description = ""
authors = ["Kousuke Ebihara <kousuke@co3k.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
